---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo = FALSE}
if (!file.exists("activity.csv") )
    {
     dlurl <- 'http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip'  
     download.file(dlurl,destfile='repdata%2Fdata%2Factivity.zip',mode='wb')  
     unzip('repdata%2Fdata%2Factivity.zip')
    }

# Read data
data <- read.csv("activity.csv")  
```

## What is mean total number of steps taken per day?

```{r, echo =FALSE}
steps_by_day <- aggregate(steps ~ date, data, sum)
hist(steps_by_day$steps, main = paste("Total Steps Each Day"),xlab="Number of Steps")
```

### Mean
```{r,echo = FALSE}
rmean <- mean(steps_by_day$steps)
rmean
```

### Median
```{r,echo = FALSE}
rmedian <- median(steps_by_day$steps)
rmedian
```

## What is the average daily activity pattern?

```{r,echo = FALSE}
steps_by_interval <- aggregate(steps ~ interval, data, mean)
plot(steps_by_interval$interval,steps_by_interval$steps, type="l", xlab="Interval", ylab="Number of Steps",main="Average Number of Steps per Day by Interval")
```

### Interval with most average steps
```{r, echo = FALSE}
max_interval <- steps_by_interval[which.max(steps_by_interval$steps),1]
max_interval
```

## Imputing missing values

### Total Missing Values
```{r, echo = FALSE}
NATotal <- sum(!complete.cases(data))
NATotal
```

```{r, echo = FALSE}
StepsAverage <- aggregate(steps ~ interval, data = data, FUN = mean)
fillNA <- numeric()
for (i in 1:nrow(data)) {
    obs <- data[i, ]
    if (is.na(obs$steps)) {
        steps <- subset(StepsAverage, interval == obs$interval)$steps
    } else {
        steps <- obs$steps
    }
    fillNA <- c(fillNA, steps)
}
```

```{r, echo = FALSE}
new_activity <- data
new_activity$steps <- fillNA
```

```{r, echo = FALSE}
StepsTotalUnion <- aggregate(steps ~ date, data = new_activity, sum, na.rm = TRUE)
hist(StepsTotalUnion$steps, main = paste("Total Steps Each Day"), col="grey", xlab="Number of Steps")
#Create Histogram to show difference. 
hist(steps_by_day$steps, main = paste("Total Steps Each Day"), col="black", xlab="Number of Steps", add=T)
legend("topright", c("Imputed", "Non-imputed"), col=c("grey", "black"), lwd=10)
```
### Mean
```{r, echo = FALSE}
rmeantotal <- mean(StepsTotalUnion$steps)
rmeantotal
```

### Median
```{r, echo = FALSE}
rmediantotal <- median(StepsTotalUnion$steps)
rmediantotal
```

### Diff in Median
```{r, echo = FALSE}
rmediandiff <- rmediantotal - rmedian
rmediandiff
```

### Diff in Mean
```{r, echo = FALSE}
rmeandiff <- rmeantotal - rmean
rmeandiff
```
## Are there differences in activity patterns between weekdays and weekends?

```{r, echo= FALSE}
weekdays <- c("Monday", "Tuesday", "Wednesday", "Thursday", 
              "Friday")
new_activity$dow = as.factor(ifelse(is.element(weekdays(as.Date(new_activity$date)),weekdays), "Weekday", "Weekend"))
StepsTotalUnion <- aggregate(steps ~ interval + dow, new_activity, mean)
library(lattice)
xyplot(StepsTotalUnion$steps ~ StepsTotalUnion$interval|StepsTotalUnion$dow, main="Average Steps per Day by Interval",xlab="Interval", ylab="Steps",layout=c(1,2), type="l")
```

